greenbone/gsad

.docker/build.Dockerfile, .docker/main.Dockerfile
**What**:
Use unstable container image tags a basis image
**Why**:
Using main was a naming mistake.
**How**:
**Checklist**:
=> Use unstable container image tags a basis image

.github/CODEOWNERS
**What**:
**Why**:
**How**:
**Checklist**:
=> Change maintainers of repository

.docker/build.Dockerfile, .docker/prod.Dockerfile, .github/workflows/ci-c.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container.yml, .github/workflows/release-pontos-manually.yml, .github/workflows/release-pontos-patch.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> [CI] No more clang, add release workflow

.docker/prod.Dockerfile
**What**:
**Why**:
**How**:
**Checklist**:
=> Fix prod.Dockerfile

changelog.toml
**What**:
**Why**:
**How**:
**Checklist**:
=> Add changelog.toml

CMakeLists.txt, changelog.toml
**What**:
**Why**:
**How**:
**Checklist**:
=> Update version 21.10->22.4

.docker/start-gsad.sh
**What**:
Update gsad startup in container
**Why**:
Don't run gsad in foreground to get log output.
When using -f to start gsad the tail command will never be executed.
**How**:
**Checklist**:
=> Update gsad startup in container

.docker/entrypoint.sh, .docker/prod.Dockerfile, .github/CODEOWNERS
**What**:
Use entrypoint file for switching to gsad user
**Why**:
This allows for accessing the container as a different user more easily.
**How**:
**Checklist**:
=> Use entrypoint file for switching to gsad user

.github/workflows/container.yml
**What**:
**Why**:
Provide images for arm64
**How**:
**Checklist**:
=> Also build container images for arm64

.github/dependabot.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Use dependabot for updating GitHub actions

.github/workflows/container.yml
**What**:
Allow trigger a new build from gvm-libs repository after changes are going into main
**Why**:
**How**:
**Checklist**:
=> Lets trigger new container build from gvm-libs

.docker/build.Dockerfile, .docker/prod.Dockerfile, .github/workflows/ci-c.yml, .github/workflows/codeql-analysis.yml, .github/workflows/container.yml
**What**:
**Why**:
**How**:
**Checklist**:
=> Cleanup Docker

.docker/build.Dockerfile, .docker/prod.Dockerfile, .github/workflows/ci-c.yml, .github/workflows/codeql-analysis.yml
**What**:
Update workflows and dockerfiles for oldstable branch
**Why**:
**How**:
**Checklist**:
=> New workflows and dockerfiles for oldstable branch

.docker/build.Dockerfile, .docker/prod.Dockerfile, .github/workflows/ci-c.yml, .github/workflows/codeql-analysis.yml
**What**:
Update dockerfiles and workflows for stable branch
**Why**:
**How**:
**Checklist**:
=> Update dockerfiles and workflows for stable branch

.github/workflows/build-container.yml, .github/workflows/container.yml
**What**:
* Build container images for pull requests too
* Split creating build and production images
**Why**:
**How**:
**Checklist**:
=> Improve container builds

src/gsad_gmp.c, src/gsad_gmp_auth.h, src/gsad_user.c
**What**:
Send GMP logout command when logging out a user, clearing the authentication cache in gvmd.
**Why**:
GEA-36
**How**:
**Checklist**:
=> Send GMP logout command when logging out a user

src/gsad_http_handler.c
Make init_http_handlers easier to follow.
I struggled.
=> Clean: init_http_handlers

.github/workflows/push.yml
Add: Push workflow for greenbone registry
DEVOPS-1073
DEVOPS-1073
=>  Add: Push workflow for greenbone registry 

src/gsad_gmp.c
Remove unnecessary content from get_system_reports response
The now removed content was a leftover from the old XSLT based GSA version and is not uses in the React based GSA.
=> Remove unnecessary content from get_system_reports response

src/gsad.c, src/gsad_gmp.c, src/gsad_gmp.h, src/gsad_validator.c
Add Agent Group endpoints and validation
This initial logic will handle the basis CRUD logic for agent groups.
https://jira.greenbone.net/browse/GEA-976
=> Initial agent groups logic

README.md
f9adf19941cd85cb646816bf7600cb8df5f86c5f bumped the cmake requirement to 3.5, do that in the readme too.
To lower the surprise factor.
=> Harmonise cmake prerequisite in readme with cmake list

src/gsad.c, src/gsad_gmp.c, src/gsad_gmp.h, src/gsad_validator.c
Adapted the modify_agents command to the new agent data structure.
The data structure of the agents in agent-control changed.
GEA-966
Tested manually on my local development system
=> Change: Adapted the modify_agents command to the new agent data structure.

src/gsad.c, src/gsad_gmp.c, src/gsad_gmp.h, src/gsad_validator.c
Added the "modify_agent_control_scan_config_gmp ()" function to gsad.
This function is needed to modify the scan config of a given agent control.
GEA-1259
Tested manually on my local development system.
=> Added the "modify_agent_control_scan_config_gmp ()" function to gsad.
