greenbone/gsad

.docker/main.Dockerfile

**What**:
Use a dedicated user for gsad, set unix socket locations on startup and
use a vendor version by default.
**Why**:
When starting the gsad container it should not run as root and the runtime directories should be separated (which is not possible completely yet).
**How**:
**Checklist**:

Improve dockerfile for gsad

---

.docker/gsad_log.conf
.docker/prod.Dockerfile

**What**:
Configure logging and use sane defaults for unix sockets.
**Why**:
Getting logging output is necessary for debugging gsad issues and using /run/gvm/gsad for the gsad unix socket location via mounting a docker volume doesn't work for unknown reasons.
**How**:
**Checklist**:

Improve container

---

.docker/prod.Dockerfile
CMakeLists.txt
src/CMakeLists.txt
src/gsad.c
src/gsad_gmp.c

**What**:
The calls of pidfile_create and pidfile_remove are adjusted to use a
full path defined by GSAD_PID_PATH.
The new path GSAD_RUN_DIR is specific to gsad and GVMD_RUN_DIR only
has to be shared with gvmd and other modules using GMP via file socket.
**Why**:
To make gsad work correctly with the changes in greenbone/gvm-libs/pull/626 (AP-1789)
**How**:
**Checklist**:

CHANGE: Use full path GSAD_PID_PATH for PID files, change GVM_RUN_DIR to GSAD_RUN_DIR, GVMD_RUN_DIR 

---

src/gsad.c
src/gsad_gmp.c
src/gsad_gmp.h

**What**:
Added the gmp handler function "save_license_gmp (..)" that creates
a GMP request to add or modify the given license.
**Why**:
This implementation is part of the Theia license project.
Addresses AP-1569.
**How**:
**Checklist**:

Added a function that creates a GMP request to update a license.

---

src/gsad_gmp.c

**What**:
If a GMP response contains status 503 (Service Unavailable), gsad will
now also use 503 as the HTTP response code.
**Why**:
To differentiate these errors from other errors like invalid requests.
AP-1570
**How**:
Requested the license page when gvmd was built with licensing enabled
but the theia service was not running and checked the HTTP status in the
browser dev tools.
**Checklist**:

Add status 503 case to set_http_status_from_entity

---

.docker/prod.Dockerfile
.docker/start-gsad.sh

**What**:
Add an extensible start script for gsad to the container image.
**Why**:
Allow for easier adjusting the start parameters of gsad while always displaying the log output.
**How**:
Tested the container locally.
**Checklist**:

Improve gsad container start

---

src/gsad.c

**What**:
The order of the parameters of the function MHD_start_daemon (...)
was changed to get rid of warning messages.
**Why**:
This is a bug-fix.
Addresses AP-1929. 
**How**:
Started gsad several times and checked the log messages.
**Checklist**:

Changed the order of the parameters of MHD_start_daemon (...)

---

CMakeLists.txt

Installing the empty GSAD_RUN_DIR serves no purpose. The run(-time)
directories of services should be dynamically created and not
statically installed. And gsad's systemd service file ensures that the
PIDFile is created, which is the only content of gsad's run
directory. And even if there would be further content, then systemd's
RuntimeDirectory directive should be used instead (as it is already
done for gvmd).
The bottom line is: in no case should run-time directories be
installed, they are to be created at *run-time*.

[CMake] Do not install run(-time) dir(ectory)

---

config/gsad.service.in

Specifying the Group is typically never required, as systemd's default
behavior to use the user's primary group is what you want anyways. And
to make the service file more readable, unnecessary directives should
be removed. So this removes the Group= directive.

[gsad.service] Drop Group= directive

---

config/gsad.service.in

Just like the other Greenbone Vulnerability Assistant daemons, e.g.,
gvmd, when run under systemd, gsad needs to instruct systemd to create
the runtime directory /run/gsad (assuming $GSAD_PID_PATH is the
default of /run/gsad/gsad.pid).

[gasd.service] Add RuntimeDirectory=gsad

---

config/gsad.service.in

`Type=forking` leads to problems (eg: https://forum.greenbone.net/t/gsad-service-activating/12993/13) and is unnecessary since gsad has a `--foreground` option.
**What**:
Switch gsad.service unit file from `Type=forking` to `Type=exec`
**Why**:
systemd appears to lose track of the gsad process when using `Type=forking` and become unable to stop the service, which then prevents the service from being later restarted (because it was never actually stopped).
**How**:
I've been running this configuration across multiple systems for a while, and
1. it solves the service shutdown/startup problems
2. it doesn't appear to cause any new problems
**Checklist**:

Change service start up type from forking to exec

---

src/gsad.c

**What**:
Ensure our used regular expressions are pcre 2 compatible to fix support of glib2.0 >= 2.73.2
DEVOPS-426
Fixes #86
**Why**:
glib changed their internal regexp library to use pcre 2 in a minor release (!) with version 2.73.2. This breaks some of our regular expressions.
**How**:
**Checklist**:

Fix: Fix regex for new glib2.0 >= 2.73.2

---

src/gsad.c

**What**:
Allow users to add curved brackets for name fields like target name. This seems to have worked before the pcre2 adjustments.
Additionally allow the en dash Unicode character (U+2013) for name and comment fields.
Closes #89
DEVOPS-475
**Why**:
All three characters seem to have worked before. Thus this PR is fixing a regression.
**How**:
Build a new GSA docker container with changed regrexps and tried to create a target including the new characters.

Fix: Allow brackets and en dash Unicode character in name and comment fields

---

.docker/build.Dockerfile

**What**:
Add libcgreen1-dev package to the build container image. cgreen is a library for C based unit tests.
**Why**:
The library is necessary to build and run the new unit tests.
**How**:
**Checklist**:

Add: Add libcgreen1-dev package to build container

---

.github/workflows/ci-c.yml

**What**:
Use gsad stable build image to run the unit test in stable branch
**Why**:
Stable branch should use stable container images.
**How**:
**Checklist**:

Use gsad stable build image to run the unit test in stable branch

---

src/gsad_http.c

**What**:
Only allow access to the session cookie from the same site and not for third parties. This avoids CSRF attacks like like e.g. [BREACH](http://breachattack.com/).
For more details please take a look at
http://www.sjoerdlangkemper.nl/2016/04/14/preventing-csrf-with-samesite-cookie-attribute/
**Why**:
This fix was missing in the main and stable branches after moving gsad from the gsa repository to its own.
**How**:
**Checklist**:

Avoid cross origin forgery by using same-site cookie

---

src/gsad_gmp.c

Use MHD_HTTP_UNPROCESSABLE_CONTENT instead of deprecated MHD_HTTP_UNPROCESSABLE_ENTITY for libmicrohttpd 9.74 and later.
Gets build working when CMAKE_BUILD_TYPE is DEBUG.
Was deprecated [in this commit](https://github.com/Karlson2k/libmicrohttpd/commit/8c644fc1f4d498ea489add8d40a68f5d3e5899fa).

Use MHD_HTTP_UNPROCESSABLE_CONTENT for 9.74 or later

---

src/gsad_gmp.c
src/gsad_validator.c

This adds an extra authentication option to force LDAPS for LDAP authentication
The normal LDAP port may be blocked by a firewall, in which case only the LDAPS port should be tried.
GEA-82
requires greenbone/gvm-libs/pull/747 and greenbone/gvmd/pull/1928 to work properly

Add option to force LDAPS for authentication

---

src/gsad_log_conf.cmake_in

New section in log configuration for G_LOG_DOMAIN "gsad vali".  Covers logs from file src/validator.c.
Handy to skip some logs when enabling others.

Add section to log conf for validator

---

.docker/build.Dockerfile
.docker/prod.Dockerfile
.github/workflows/build-container.yml
.github/workflows/container.yml

When building Docker images for release tags, use the oldstable gvm-libs image and stable build image.
Otherwise use the oldstable-edge gvm-libs and edge build image.

Change: Use (old)stable for release Docker images

---

src/gsad_gmp.c

Use the new GET_NVTS skip_cert_refs flag to speed up get_config_family.
With greenbone/gvmd/pull/2009 the Edit dialog for config family Databases opens in about 10s.  With this PR it opens in about 5s.
The Edit Config Family dialog opens too slowly.
Requires greenbone/gvmd/pull/2010.

Change: Skip CERT refs in get_config_family

---

src/gsad_gmp.c

This adds scp_port as a valid option in the checks in append_alert_method_data.
So it can be set by GSA as an option for SCP alerts.
GEA-280
uses greenbone/gvmd#2057

Add: Add scp_port as valid alert method data key

---

src/gsad_gmp.c

The option Pagination was added to the "Compose Content for Scan Report" dialog for alerts. The default of this option is ignore, so that all results are included in the report regardless of the number of rows specified in the filter selected in the dialog.
This is an improvement that belongs to a bug-fix.
GEA-124

Add: Added an option to ignore the pagination for alert reports.

---

src/gsad_gmp.c

Use the new GET_NVTS skip_tags flag to speed up get_config_family.
The Edit Config Family dialog opens too slowly.
Requires greenbone/gvmd/pull/2070.

Change: Skip tags in get_config_family

---

README.md
src/CMakeLists.txt
src/gsad.c

In exec_gmp_get, compress responses with deflate (zlib).
Speeds up data transfer by reducing size of transfer.  Helps especially when the network is slow and pages are sending many MB. For example, the edit_config_family request when editing family 'Databases' with 'good 2g' throttling:
```
main: 58s
patch: 6s
```

Add: compress responses in exec_gmp_get

---

src/gsad_gmp.c
src/gsad_gmp_arguments.c

Always use the return from g_string_free when stealing the string.
In `restore_gmp` and `empty_trashcan_gmp` prevent the steal by removing unused XML returns.
Prevents warnings with glib 2.76.

Use result of g_string_free when arg 2 is FALSE

---

src/gsad.c
src/gsad_gmp.c
src/gsad_gmp.h
src/gsad_http_handler.c

Remove response_data arg from manager_connect.
In the past this was used to set the return code, but the caller's now do it.
Usage remove in c023ad363e430c72212d5da27354694296b49f4d.

Change: remove old arg from manager_connect

---

src/gsad_gmp.c

Use the new GET_NVTS lean flag to speed up get_config_family.
The Edit Config Family dialog opens too slowly.
Requires greenbone/gvmd/pull/2077.

Change: Use lean in get_config_family

---

src/gsad.c

Initialize the compressed response pointer.
To avoid warning about being used without initialization.
GEA-336

Fix: Add initialization to remove warning

---

README.md
src/CMakeLists.txt
src/gsad.c

In exec_gmp_get, compress responses with Brotli.
This feature is only used if libbrotli is found at build time.
Speeds up data transfer by reducing size of transfer.
Results in smaller sizes than deflate. For example one `cmd=edit_config_family` request of 1.52MB:
```
br  73.04kB
de 107.38kB
```
Recent PR for deflate: greenbone/gsad/pull/143
Brotli encoding C man page: https://man.archlinux.org/man/core/brotli/encode.h.3.en

Add: compress responses in exec_gmp_get with Brotli

---

src/gsad.c

Remove test output of brotli compression
This was generating unnecessary log entries when brotli compression was enabled.

Fix: Remove test output of brotli compression

---

src/gsad_http_handler.c

Update directory name for assets URL handler to `assets` instead of `static` and remove sub-directories.
After switching to Vite as a build tool for GSA, all assets are placed by default in the `assets` directory without creating sub-directories for each type.
GEA-541

Change: Update directory name for assets url handler

---

src/gsad.c

Adjust content security policy to allow inline javascript
Inline javascript is used by the build tool to detect older versions of browsers. Without adjusting the content security policy we aren't able to support older browsers.

Change: Adjust content security policy to allow inline javascript

---

src/gsad_gmp.c

Escape comments when creating or modifying targets.
Comments should be escaped but they were not. An error occurs when adding an ampersand to the comment field.
GEA-562

Fix: Comments should be escaped when creating or modifying targets.

---

.github/workflows/ci-c.yml
CMakeLists.txt
src/CMakeLists.txt

This adds new targets for measuring unit test coverage that can be enabled with the CMake option ENABLE_COVERAGE.
The GitHub Actions workflow now also generates the coverage report and uploads it to Codecov.
GEA-604

Add: Coverage CMake targets and Codecov upload

---

src/gsad_gmp.c

In addition to the GMP HELP command for the list of available commands, get_capabilities_gmp will also run GET_FEATURES to get the list of optional features.
This will allow GSA to get the state of feature toggles like OPENVASD or CVSS3_RATINGS.
GEA-612

Add: Use GMP GET_FEATURES in get_capabilities_gmp

---

src/gsad_gmp.c

Before trying to get the report configs for new alerts, check if the get_report_configs command is available.
This prevents errors in case the command is not available.
GEA-647

Fix: Make report configs optional for new alerts

---

src/gsad_gmp.c
src/gsad_validator.c

- Add usage_type parameter to GMP get_reports.
- Allow sub-types (audit_report, audit and policy) as resource types
- get_reports can now be used to get a report by its usage type (scan/audit). This is used by GSA's dedicated views for both scan and audit reports.
GEA-397
requires [greenbone/gvmd#2125](https://github.com/greenbone/gvmd/pull/2125)

Change: Add usage_type parameter to GMP get_reports.

---

.docker/build.Dockerfile
.docker/prod.Dockerfile

Update gvm-libs image in prod.Dockerfile and build.Dockerfile
In the next release gvm-libs will be pushed to a new registry, therefore the reference needs to be updated.
https://jira.greenbone.net/browse/DEVOPS-1229

Change: Update gvm-libs image in prod.Dockerfile and build.Dockerfile

---

src/gsad_gmp.c
src/gsad_validator.c

Allows the update of setting variables for time and date formats.
To allow updating time and date formats from GSA user settings independently of the language.
GEA-430
requires [#2283](https://github.com/greenbone/gvmd/pull/2283)

Add: Allow the update of setting variables for time and date formats

---

src/CMakeLists.txt
src/gsad_gmp.c

Use pkg-config to configure libgcrypt.
libgcrypt-config has been dropped.
Closes #181.

Fix: CMake: Use pkg-config instead of the dropped libgcrypt-config

---

src/gsad_validator.c

The params "levels", "threat", "new_threat", "level_high", "level_medium", "level_low", "level_log", and "level_false_positive" are removed from the validator.
These params are no longer used.
GEA-726

Remove: Threat, levels params from validator

---

config/CMakeLists.txt

By default install the systemd files into `/usr/local/lib/systemd/system`.
`/lib` is only a symlink to `/usr/lib` with the [usr merge](https://wiki.debian.org/UsrMerge) process. 
`/lib` being only symlink let the Dockerfile copy command `COPY /install/ /` fail with Debian >= bookworm.
Implement a similar change as in https://github.com/greenbone/gvmd/pull/2304
Tested the Docker build locally.
https://jira.greenbone.net/browse/GEA-791

Fix: Add LIBDIR to SYSTEMD_SERVICE_DIR config

---

src/gsad_gmp.c
src/gsad_validator.c

The use of the Kerberos credential type is now also  allowed / possible in gsad.
This will later be used in scan targets for Kerberos 5 authentication.
GEA-776

Add: Added the Kerberos credential type to gsad.

---

src/gsad.c
src/gsad_http.c
src/gsad_http_handler.c

Handle manual URL as static content
For static content an index.html is returned if available when a directory is requested. If the URL points to a directory but the URL doesn't end with a slash a redirect response with a URL including the slash is returned. With this change gsad behaves more like a "normal" http server when serving static content for the manual.
https://jira.greenbone.net/browse/GEA-892

Handle manual URL as static content

---

.docker/gsad_log.conf
README.md
src/gsad_log_conf.cmake_in

Simplify logging configuration
The `*` section sets the default of all other logging categories. Therefore only the different values need to be set. Additionally use the level names instead of the numbers. It's difficult to remember which number represents wich level in glib logging.

Simplify logging configuration

---

.docker/gsad_log.conf
src/gsad_gmp.c

Fix typo in logging domain for gsad_gmp module
The logging domain contained an extra space.
https://github.com/greenbone/gsad/pull/194

Fix typo in logging domain for gsad_gmp module

---

src/gsad_gmp.c

Add missing check of `passwd`.
All the params should be checked. `text` was being checked twice.
This looks like a typo from e2e43458b9975a11130c3efe7c2c861ece4e74b8. See line [17139](https://github.com/greenbone/gsad/commit/e2e43458b9975a11130c3efe7c2c861ece4e74b8#diff-b581a6dd0d2f741e26f074617e97ac04b34bced71b0a82c92d5cb5ff5d176420L17139) of gsad_gmp.c.

Fix: check passwd in save_my_settings_gmp

---

.github/workflows/ci-c.yml

Use correct container image URL for running unit tests
Don't use an outdated and now unavailable container image URL for gvm-libs stable image.

Use correct container image URL for running unit tests

---

CMakeLists.txt
README.md
src/gsad.c
src/gsad_gmp.c
src/gsad_gmp.h
src/gsad_validator.c
src/gsad_validator_test.c

Added GMP support for:
- `get_agent_installers_gmp`: List available agent installers
- `get_agent_installer_gmp`: Get metadata for a single agent installer
- `get_agent_installer_file_gmp`: Get the installer file (base64-encoded)
- `delete_agent_installer_gmp`: Delete an agent installer
These changes are needed for Agent Installer integration.
GEA-1038

Add: Add get, list, and delete agent installer commands

---

src/gsad_http_handler.c

Handle get_system_report failure more gracefully
Send a better error message in case a system report can't be requested from gvmd.

Handle get_system_report failure more gracefully

---

src/gsad_gmp.c

Fixed a little problem regarding the credential_id that otherwise
would occur when working with the new agent scanner.
This is needed for the new agent scanner.
GEA-964

Fixed a little credential_id problem.

---

src/gsad_gmp.c
src/gsad_gmp.h

Fixes mismatched return types and syntax errors in agent group GMP functions.
To ensure the code compiles correctly and function declarations match their implementations.

Fix: resolve type mismatches and syntax errors in agent group GMP handlers

---

src/gsad_gmp.c

Update save_setting command to make setting_id optional
Allow to change `Timezone` and `Password` via save_setting which both are identified by name and not UUID according to
https://docs.greenbone.net/API/GMP/gmp-22.6.html#command_modify_setting
Therefore use name if provided otherwise require id.
https://jira.greenbone.net/browse/GEA-1144

Update save_setting command to make setting_id optional

---

src/gsad.c
src/gsad_gmp.c
src/gsad_gmp.h
src/gsad_validator.c

Introduce new change_password API command
Allow to change the password in a single command instead of using save_my_settings.
https://jira.greenbone.net/browse/GEA-1144

Introduce new change_password API command

---

.github/workflows/ci-c.yml
.github/workflows/codeql-analysis.yml
.github/workflows/container.yml

Allow to run our CI pipeline from GitHub forks
Allow to run most parts of the CI/CD pipeline on forks too.
For whatever reason the vars GitHub context is not available in forks. Therefore the container couldn't be downloaded.
https://github.com/greenbone/gsad/pull/216

Allow to run our CI pipeline from GitHub forks

---

src/gsad.c

Allow images to be delivered as src="data:"
Extends our default content security policy to allow images be provided as `<img src="data:..."/>`. This is used to provide the charts for the system reports.
https://jira.greenbone.net/browse/GEA-1197

Allow images to be delivered as src="data:"

---

src/gsad.c
src/gsad_gmp.c
src/gsad_gmp.h
src/gsad_validator.c

The delete_agent_installer command is removed.
The command is removed from gvmd / GMP so it should be removed here as well.
GEA-1224
greenbone/gvmd/pull/2516

Remove delete_agent_installer command

---

.docker/prod.Dockerfile
.github/workflows/container.yml
CMakeLists.txt

Allow to build arbitrary container images
Enable to build container images with different feature sets enabled. Currently the agents feature set gets uploaded into a specific container image. The agents container images get pushed to to gchr.io only.
This PR also creates container images for every PR and uploads them to ghcr.io.
https://jira.greenbone.net/browse/GEA-1139

Allow to build arbitrary container images

---

src/gsad_validator.c

Added agent_group to the list of supported values in resource_type validation.
agent_group was missing from the validation, which caused requests using this resource type to fail.
GEA-1278

Fix: missing agent_group in resource_type validation
